Repository ambassify/react-avatar, pull requests merged in 2018-12, with the labels that each got.

#149 [vkontakte] use avatar redirect for Vkontakte
  demo/index.js
  src/index.js
  src/sources/Vkontakte.js
Labels: bug

#134 improve font-size consistency with textMarginRatio property
  README.md
  demo/index.js
  index.d.ts
  src/index.js
Labels: help wanted, question

#150 [text scaling] resolves scaling issue in IE11 (#142)
  src/index.js
Labels: bug

#145 Add Github Handle fetch support
  README.md
  demo/index.js
  index.d.ts
  src/index.js
  src/sources/Github.js
Labels: enhancement
